Repository csvalpha/amber-ui, pull requests merged in 2020-03, with the labels that each got.

#99 Feature/fetch
  app/components/tools/closing-activities.js
  app/components/tools/daily-verse.js
  app/components/tools/forum-posts.js
  app/components/tools/recent-photo-comments.js
  app/components/tools/recent-polls.js
  app/components/tools/upcoming-activities.js
  app/components/tools/upcoming-birthdays.js
  app/components/users/otp-settings.js
  app/components/users/password-settings.js
  app/controllers/activities/mail-enrolled.js
  app/controllers/groups/export.js
  app/controllers/mail-aliases/index.js
  app/controllers/mail-moderations/accept.js
  app/controllers/mail-moderations/index.js
  app/controllers/mail-moderations/reject.js
  app/controllers/photo-albums/new.js
  app/controllers/photo-albums/photo-album/edit.js
  app/controllers/users/activate-account.js
  app/controllers/users/batch/new.js
  app/controllers/users/edit.js
  app/controllers/users/forgot-password.js
  app/controllers/users/resend-activation.js
  app/routes/debit/collections/sepa.js
  app/services/ajax.js
  app/services/fetch.js
  app/services/message-bus.js
  app/services/session.js
  app/templates/components/tools/upcoming-birthdays.hbs
  package.json
  tests/unit/components/tools/upcoming-birthdays-test.js
  yarn.lock
Labels: status:ready to review

#121 Remove deprecations
  app/controllers/groups/edit.js
  app/controllers/groups/export.js
  app/controllers/oauth/authorize.js
  app/controllers/photo-comments/index.js
  app/controllers/users/batch/new.js
  app/mixins/form-load-or-create-mixin.js
  app/models/form/response.js
  app/routes/forum/categories/category/threads/thread/posts/index.js
  app/routes/oauth/authorize.js
  app/templates/oauth/authorize.hbs
  tests/helpers/start-app.js
  tests/unit/components/form/response/response-form-test.js
Labels: status:ready to review

#124 Fix manifest path
  app/index.html
Labels: automerge

#122 Replace analytics
  app/index.html
  app/router.js
  config/environment.js
  package.json
  yarn.lock
Labels: status:ready to review

#118 fixes floating point inaccuracies in debit collections
  app/controllers/debit/collections/show.js
Labels: automerge

#120 Do not bubble actions to parent
  app/components/form/closed-question.js
  app/components/form/form-form.js
  app/components/form/open-question.js
  app/components/form/response/response-card.js
  app/components/forum/forum-post-new.js
  app/controllers/activities/show.js
  app/controllers/forum/categories/category/threads/thread/posts/index.js
  app/routes/forum/categories/category/threads/thread/posts/index.js
  app/services/session.js
  app/templates/activities/show.hbs
  app/templates/components/form/form-form.hbs
  app/templates/forum/categories/category/threads/thread/posts/index.hbs
Labels: automerge, status:ready to review

#130 Fix sorting of birthday tool
  app/components/tools/upcoming-birthdays.js
  app/templates/components/tools/upcoming-birthdays.hbs
Labels: automerge

#129 Fix oauth login
  app/routes/oauth/authorize.js
Labels: automerge

#87 Feature/privacy modal
  app/components/privacy-modal.js
  app/templates/components/basic-modal.hbs
  app/templates/components/privacy-modal.hbs
Labels: automerge, status:ready to review

#109 Feature/sog name trainer
  app/abilities/sog.js
  app/abilities/sog/name-trainer.js
  app/controllers/sog/name-trainer.js
  app/router.js
  app/routes/sog/index.js
  app/routes/sog/name-trainer.js
  app/styles/app.scss
  app/styles/modules/card.scss
  app/styles/routes/sog/name-trainer.scss
  app/templates/components/menu-sidebar.hbs
  app/templates/sog/index.hbs
  app/templates/sog/name-trainer.hbs
  config/environment.js
  mirage/factories/group.js
  mirage/factories/membership.js
  mirage/factories/user.js
  mirage/scenarios/default.js
  tests/unit/routes/sog/index-test.js
  tests/unit/routes/sog/name-trainer-test.js
  translations/en.yaml
  translations/nl.yaml
  yarn.lock
Labels: status:ready to merge

#137 Fix activity and poll loading
  app/templates/activities/index.hbs
  app/templates/components/tools/closing-activities.hbs
  app/templates/components/tools/recent-polls.hbs
  app/templates/components/tools/upcoming-activities.hbs
Labels: automerge, type:bug

#136 Fix the logout bug
  app/authenticators/oauth2.js
  app/authorizers/oauth2.js
  app/controllers/login.js
  app/routes/login.js
  package.json
  yarn.lock
Labels: automerge

#138 Hotfix sog page
  app/controllers/sog/name-trainer.js
  app/templates/sog/name-trainer.hbs
Labels: automerge
