Repository csvalpha/amber-ui, pull requests merged in 2020-02, with the labels that each got.

#110 Add missing FontAwesome icons
  config/environment.js
Labels: automerge, type:bug

#112 Fix markdown editor
  app/templates/components/md-editor.hbs
  app/templates/components/md-editor/md-editor-toolbar.hbs
Labels: automerge, type:bug

#113 Update README.md
  README.md
Labels: status:ready to merge

#105 Make Ember-Simple-Auth send client id as query param
  app/authenticators/oauth-2.js
Labels: status:ready to review

#114 Add Bandwidth Limit Exceeded error explanation
  app/controllers/error.js
Labels: status:ready to merge

#107 Ember 3.6
  .eslintignore
  .eslintrc.js
  .template-lintrc.js
  MODULE_REPORT.md
  README.md
  app/components/lustrum/lustrum-bar.js
  app/routes/users/index.js
  app/templates/activities/ical.hbs
  app/templates/components/form/closed-question.hbs
  app/templates/components/form/consumption-list.hbs
  app/templates/components/form/responses-table-totals.hbs
  app/templates/components/forum/forum-post.hbs
  app/templates/components/input/select-input.hbs
  app/templates/components/md-editor/md-editor-toolbar.hbs
  app/templates/components/model-form/checkbox-group.hbs
  app/templates/components/model-form/radio-group.hbs
  app/templates/components/poll/closed-question.hbs
  app/templates/groups/export.hbs
  config/optional-features.json
  package.json
  tests/unit/components/form/response/response-form-test.js
  tests/unit/components/link-to-test.js
  tests/unit/controllers/groups/edit-test.js
  tests/unit/helpers/form-opened-label-test.js
  tests/unit/helpers/lowercase-test.js
  tests/unit/helpers/range-test.js
  tests/unit/helpers/youtube-regex-test.js
  tests/unit/initializers/model-save-if-dirty-test.js
  tests/unit/instance-initializers/store-on-app.js
  tests/unit/mixins/authorization-route-mixin-test.js
  tests/unit/mixins/rollback-model-on-deactivation-route-mixin-test.js
  tests/unit/models/permission-test.js
  tests/unit/models/user-test.js
  tests/unit/routes/activities/print-enrolled-test.js
  tests/unit/routes/articles/edit-test.js
  tests/unit/routes/articles/index-test.js
  tests/unit/routes/articles/new-test.js
  tests/unit/routes/articles/show-test.js
  tests/unit/routes/groups/edit-test.js
  tests/unit/routes/groups/new-test.js
  tests/unit/routes/polls/destroy-test.js
  tests/unit/routes/polls/edit-test.js
  tests/unit/routes/polls/index-test.js
  tests/unit/routes/polls/new-test.js
  tests/unit/routes/polls/show-test.js
  tests/unit/routes/users/edit-test.js
  tests/unit/routes/users/index-test.js
  tests/unit/routes/users/new-test.js
  tests/unit/services/layout-manager-test.js
  yarn.lock
Labels: status:ready to review

#116 Crop images
  public/advertisements/knaek.png
  public/advertisements/sponsorkliks.png
  public/images/frontpage/afke.jpg
  public/images/frontpage/laurens.jpg
  public/images/frontpage/luuk.jpg
  public/images/frontpage/susan.jpg
Labels: automerge, status:ready to merge
