Repository csvalpha/amber-ui, pull requests merged in 2020-01, with the labels that each got.

#86 Hide username and make email required
  app/templates/users/form.hbs
Labels: automerge

#84 Update eslint and ember-suave
  .eslintrc.js
  app/abilities/forum/post.js
  app/adapters/application.js
  app/components/form/status-icon.js
  app/components/form/status-tag.js
  app/components/menu-sidebar-item.js
  app/components/model-form/checkbox-button.js
  app/components/permissions/permissions-table-item.js
  app/components/poll/closed-question.js
  app/components/poll/poll-form.js
  app/components/poll/status-tag.js
  app/components/quick-post.js
  app/components/tools/board-room-presence.js
  app/components/tools/upcoming-activities.js
  app/components/tools/upcoming-birthdays.js
  app/components/users/privacy-settings.js
  app/controllers/activities/edit.js
  app/controllers/activities/ical.js
  app/controllers/articles/edit.js
  app/controllers/error.js
  app/controllers/forum/categories/category/threads/thread/posts/index.js
  app/controllers/groups/index.js
  app/controllers/photo-albums/photo-album/photos/show.js
  app/controllers/photo-comments/index.js
  app/controllers/users/activate-account.js
  app/controllers/users/edit.js
  app/controllers/users/forgot-password.js
  app/helpers/range.js
  app/initializers/model-save-if-dirty.js
  app/mixins/check-if-user-is-owner-mixin.js
  app/mixins/filterable-and-sortable-mixin.js
  app/mixins/form-load-or-create-mixin.js
  app/mixins/group-memberships-mixin.js
  app/mixins/paged-model-controller-mixin.js
  app/models/activity.js
  app/models/article.js
  app/models/form/open-question.js
  app/models/form/response.js
  app/models/forum/thread.js
  app/models/group.js
  app/models/poll.js
  app/models/user.js
  app/router.js
  app/routes/activities/index.js
  app/routes/forum/categories/category/threads/new.js
  app/routes/groups/index.js
  app/routes/users/show-groups.js
  app/routes/users/show-mail.js
  app/routes/users/show-mandates.js
  app/serializers/application.js
  app/services/fetch.js
  app/services/layout-manager.js
  app/services/local-storage.js
  app/services/notification.js
  app/services/raven.js
  app/services/session.js
  package.json
  yarn.lock
Labels: automerge

#78 Fix image loading on userpage
  app/routes/users/index.js
Labels: automerge

#79 Specify used fa-icons
  app/templates/components/cards/activity-card.hbs
  app/templates/components/menu-sidebar-link.hbs
  app/templates/components/menu-sidebar.hbs
  app/templates/components/users/otp-settings.hbs
  config/environment.js
Labels: automerge

#81 Remove unused images
  public/images/alphalogonotextwhite.svg
  public/images/kylo_ren.jpg
Labels: automerge

#88 Only show closing activities when there are any
  app/templates/components/tools/closing-activities.hbs
Labels: automerge

#80 remove emoticons images
  public/emoticons/emoji_1.gif
  public/emoticons/emoji_10.gif
  public/emoticons/emoji_11.gif
  public/emoticons/emoji_12.gif
  public/emoticons/emoji_13.gif
  public/emoticons/emoji_14.gif
  public/emoticons/emoji_15.gif
  public/emoticons/emoji_16.gif
  public/emoticons/emoji_17.gif
  public/emoticons/emoji_18.gif
  public/emoticons/emoji_19.gif
  public/emoticons/emoji_2.gif
  public/emoticons/emoji_20.gif
  public/emoticons/emoji_21.gif
  public/emoticons/emoji_22.gif
  public/emoticons/emoji_23.gif
  public/emoticons/emoji_24.gif
  public/emoticons/emoji_25.gif
  public/emoticons/emoji_26.gif
  public/emoticons/emoji_27.gif
  public/emoticons/emoji_28.gif
  public/emoticons/emoji_3.gif
  public/emoticons/emoji_4.gif
  public/emoticons/emoji_5.gif
  public/emoticons/emoji_6.gif
  public/emoticons/emoji_7.gif
  public/emoticons/emoji_8.gif
  public/emoticons/emoji_9.gif
Labels: automerge

#25 Fix exif toggle button
  app/controllers/photo-albums/photo-album/photos/show.js
  app/templates/photo-albums/photo-album/photos/show.hbs
Labels: automerge

#89 Feature/lustrum
  .gitignore
  app/abilities/lustrum.js
  app/components/header-nav.js
  app/components/lustrum/lustrum-bar.js
  app/controllers/lustrum.js
  app/index.html
  app/locales/nl/translations.js
  app/router.js
  app/routes/lustrum.js
  app/styles/app.scss
  app/styles/modules/lustrum.scss
  app/templates/application.hbs
  app/templates/components/lustrum/lustrum-bar.hbs
  app/templates/components/menu-sidebar.hbs
  app/templates/lustrum.hbs
  public/images/lustrum/lustrum-lijn-kleur.svg
  public/images/lustrum/lustrum-logo-basis-kleur.svg
  translations/en.yaml
  translations/nl.yaml
Labels: automerge, status:ready to review, type:design, type:feature

#92 Fix i18n issue with lustrum page
  app/components/header-nav.js
Labels: automerge, prio:critical, type:bug

#93 Update advertisements
  app/components/advertisement-tool.js
  app/styles/components/advertisement-tool.scss
  public/advertisements/geldnl.png
  public/advertisements/inshared.png
  public/advertisements/rike.png
  public/advertisements/traffic-today.png
  tests/integration/components/advertisement-tool-test.js
Labels: automerge

#94 Hotfix staging issues
  app/helpers/capitalize-translation.js
  app/helpers/capitalize.js
  app/templates/articles/show.hbs
  app/templates/components/cards/activity-card.hbs
  app/templates/components/footer-nav.hbs
  app/templates/components/index/index-photos.hbs
  app/templates/components/lustrum/lustrum-bar.hbs
  app/templates/groups/index.hbs
  app/templates/lustrum.hbs
  app/templates/static-pages/form.hbs
  app/templates/static-pages/index.hbs
  config/environment.js
Labels: automerge, prio:critical, type:bug

#95 Fix lustrum committee group id
  app/routes/lustrum.js
Labels: automerge, type:bug

#96 Bugfix losse aanhalingstekens op lustrum pagina
  app/templates/lustrum.hbs
Labels: status:ready to merge, type:bug

#98 Set local to default nl
  app/routes/application.js
  config/ember-intl.js
Labels: automerge
