Repository csvalpha/amber-ui, pull requests merged in 2021-02, with the labels that each got.

#252 Only show status dot when with permission
  app/templates/components/tools/upcoming-activities.hbs
Labels: automerge

#251 Improve sentry logging
  Dockerfile
  Dockerfile.buildkite
  app/app.js
  app/services/raven.js
  app/services/session.js
  config/environment.js
  docker-compose.buildkite.yml
  package-lock.json
  package.json
  yarn.lock
Labels: automerge

#242 Upgrade ember
  .eslintrc.js
  app/app.js
  app/components/quick-post.js
  app/components/tools/board-room-presence.js
  app/controllers/mail-aliases/edit.js
  app/models/article.js
  app/models/user.js
  app/router.js
  app/routes/articles/show.js
  app/routes/forum/categories/category.js
  app/routes/forum/categories/category/threads/index.js
  app/routes/forum/categories/category/threads/thread.js
  app/routes/forum/categories/category/threads/thread/posts/index.js
  app/routes/groups/export.js
  app/routes/groups/show.js
  app/routes/mail-aliases/show.js
  app/routes/mail-moderations/show.js
  app/routes/photo-albums/photo-album.js
  app/routes/photo-albums/photo-album/photos/index.js
  app/routes/polls/show.js
  app/routes/static-pages/show.js
  app/routes/users/show.js
  app/templates/sog/index.hbs
  app/templates/sog/name-trainer.hbs
  package.json
  tests/test-helper.js
  yarn.lock
Labels: automerge, status:ready to review

#240 Upgrades
  .eslintrc.js
  app/templates/groups/index.hbs
  config/environment.js
  config/icons.js
  package.json
  yarn.lock
Labels: automerge

#266 Advertisement links
  app/components/advertisement-tool.js
  app/styles/components/advertisement-tool.scss
  app/templates/components/advertisement-tool.hbs
  tests/rendering/components/advertisement-tool-test.js
Labels: automerge

#268 Fix thread permission bug
  app/routes/forum/categories/category/threads/thread.js
Labels: type:bug

#274 Fix/Make OauthAuthorizeRoute an AuthenticatedRoute
  app/routes/oauth/authorize.js
Labels: type:bug

#275 Fix/Poll ability checking for memberships
  app/abilities/poll.js
  app/models/poll.js
Labels: type:bug

#278 Fix/Group recognized and rejected types
  app/models/group.js
Labels: type:bug

#277 Fix/Form status icon name
  app/templates/components/form/status-icon.hbs
Labels: type:bug

#264 New pagination style
  app/components/page-numbers.js
  app/controllers/activities/index.js
  app/controllers/articles/index.js
  app/controllers/debit/collections/index.js
  app/controllers/debit/mandates/index.js
  app/controllers/forum/categories/category/threads/thread/posts/index.js
  app/controllers/index.js
  app/controllers/photo-albums/index.js
  app/controllers/photo-comments/index.js
  app/controllers/polls/index.js
  app/controllers/static-pages/index.js
  app/controllers/users/index.js
  app/mixins/paged-model-controller-mixin.js
  app/routes/activities/index.js
  app/routes/application/application.js
  app/routes/articles/index.js
  app/routes/debit/collections/index.js
  app/routes/debit/mandates/index.js
  app/routes/forum/categories/category/threads/thread/posts/index.js
  app/routes/index.js
  app/routes/photo-albums/index.js
  app/routes/photo-albums/photo-album/photos/index.js
  app/routes/photo-albums/photo-album/photos/show.js
  app/routes/photo-comments/index.js
  app/routes/polls/index.js
  app/routes/users/index.js
  app/services/store.js
  app/templates/activities/index.hbs
  app/templates/articles/index.hbs
  app/templates/components/page-numbers.hbs
  app/templates/debit/collections/index.hbs
  app/templates/debit/mandates/index.hbs
  app/templates/forum/categories/category/threads/thread/posts/index.hbs
  app/templates/index.hbs
  app/templates/photo-albums/index.hbs
  app/templates/photo-comments/index.hbs
  app/templates/polls/index.hbs
  app/templates/users/index.hbs
  package.json
  yarn.lock
Labels: automerge, status:ready to review

#276 Fix/Readd layoutManager.closeProfileMenu
  app/services/layout-manager.js
Labels: automerge, type:bug
