Repository csvalpha/amber-ui, pull requests merged in 2022-03, with the labels that each got.

#496 Feature: Info section for potential members
  app/components/index/public.hbs
  app/components/index/public/potential-member-section.hbs
  translations/en.yaml
  translations/nl.yaml
Labels: status:ready to review, type:feature

#506 feat(ci): use .nvmrc in setup-node action
  .github/workflows/continuous-integration.yml
Labels: type:enhancement

#498 feat: actionlint
  .github/problem-matchers/actionlint.json
  .github/workflows/continuous-delivery.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/publish-image.yml
Labels: type:feature
