Repository csvalpha/amber-ui, pull requests merged in 2022-02, with the labels that each got.

#433 refactor(models): remove usage of deprecated Model.reopen
  app/initializers/model-save-if-dirty.js
  app/models/application/dirty-save.js
  app/models/form/closed-question-answer.js
  app/models/form/open-question-answer.js
  app/models/form/response.js
  app/utils/form-load-or-create.js
  tests/unit/initializers/model-save-if-dirty-test.js
  tests/unit/models/application/dirty-save.js
Labels: type:enhancement

#462 fix(response): correctly handle tracked async data
  app/components/form/responses-table-row.hbs
  app/models/form/response.js
  package.json
  yarn.lock
Labels: prio:high, type:bug

#455 feat: show numeric keyboard for OTP code
  app/components/users/otp-settings.hbs
  app/templates/login.hbs
Labels: type:feature

#467 fix: Stylelint fixes
  .github/workflows/continuous-integration.yml
  app/styles/modules/card.scss
  app/styles/modules/table.scss
  package.json
  yarn.lock
Labels: type:bug

#468 Fix activity destroy route
  app/routes/activities/destroy.js
Labels: type:bug

#483 refactor: import htmlSafe from @ember/template
  app/components/cards/frontpage-activity-card-small.js
  app/components/index/public/activities.js
  app/components/index/public/background-image.js
  app/components/index/special-promo.js
  app/components/quick-post.js
  app/controllers/polls/show.js
Labels: type:enhancement

#474 feat: run ESLint on files outside of app directory too
  .eslintrc.js
  .github/workflows/continuous-integration.yml
  .stylelintignore
  app/app.js
  app/components/tools/board-room-presence.js
  mirage/config.js
  package.json
  testem.js
  tests/helpers/create-ember-model.js
  tests/helpers/current-model-count.js
  tests/helpers/destroy-app.js
  tests/helpers/last-created-model.js
  tests/helpers/start-app.js
  tests/helpers/unit/it-should-remove-new-model.js
  tests/helpers/unit/it-should-remove-relationship.js
  tests/helpers/unit/it-should-rollback-relationship.js
  tests/helpers/unit/it-should-rollback-unsaved-changes.js
  tests/helpers/validation-error.js
  tests/helpers/validation-errors.js
  tests/unit/controllers/groups/edit-test.js
  tests/unit/helpers/form-opened-label-test.js
  tests/unit/helpers/lowercase-test.js
  tests/unit/helpers/range-test.js
  tests/unit/helpers/youtube-regex-test.js
  tests/unit/instance-initializers/store-on-app.js
  tests/unit/models/permission-test.js
  tests/unit/models/user-test.js
  tests/unit/routes/groups/edit-test.js
  tests/unit/routes/groups/new-test.js
  tests/unit/routes/users/edit-test.js
  tests/unit/routes/users/index-test.js
  tests/unit/routes/users/new-test.js
  yarn.lock
Labels: type:enhancement
